services:
  - type: web
    name: syncspace-api
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        fromConfig: true
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://syncspace-nu.vercel.app
